# Generated by Django 4.1.2 on 2023-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("Email", models.EmailField(max_length=254)),
                ("ContactNumber", models.CharField(max_length=10)),
            ],
        ),
    ]
